name: Build and test (ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: sudo apt-get install clang libc++-dev
    - name: Build library
      run: make -C sources all
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make -C sources test; ./bvm
